# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Wed Jul 23 11:43:32 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(386, 846)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.fileParameters = QtGui.QGroupBox(self.centralwidget)
        self.fileParameters.setEnabled(True)
        self.fileParameters.setFlat(False)
        self.fileParameters.setCheckable(False)
        self.fileParameters.setChecked(False)
        self.fileParameters.setObjectName(_fromUtf8("fileParameters"))
        self.gridLayout = QtGui.QGridLayout(self.fileParameters)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineFileName = QtGui.QLineEdit(self.fileParameters)
        self.lineFileName.setObjectName(_fromUtf8("lineFileName"))
        self.gridLayout.addWidget(self.lineFileName, 0, 0, 1, 2)
        self.pushNext = QtGui.QPushButton(self.fileParameters)
        self.pushNext.setObjectName(_fromUtf8("pushNext"))
        self.gridLayout.addWidget(self.pushNext, 1, 0, 1, 1)
        self.pushPrevious = QtGui.QPushButton(self.fileParameters)
        self.pushPrevious.setObjectName(_fromUtf8("pushPrevious"))
        self.gridLayout.addWidget(self.pushPrevious, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.fileParameters)
        self.EditingParamters = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EditingParamters.sizePolicy().hasHeightForWidth())
        self.EditingParamters.setSizePolicy(sizePolicy)
        self.EditingParamters.setFlat(False)
        self.EditingParamters.setCheckable(False)
        self.EditingParamters.setObjectName(_fromUtf8("EditingParamters"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.EditingParamters)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupCenter = QtGui.QGroupBox(self.EditingParamters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupCenter.sizePolicy().hasHeightForWidth())
        self.groupCenter.setSizePolicy(sizePolicy)
        self.groupCenter.setCheckable(True)
        self.groupCenter.setChecked(False)
        self.groupCenter.setObjectName(_fromUtf8("groupCenter"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupCenter)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.groupCenter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.spinCenterX = QtGui.QSpinBox(self.groupCenter)
        self.spinCenterX.setMaximum(9999)
        self.spinCenterX.setObjectName(_fromUtf8("spinCenterX"))
        self.horizontalLayout_3.addWidget(self.spinCenterX)
        self.label_2 = QtGui.QLabel(self.groupCenter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.spinCenterY = QtGui.QSpinBox(self.groupCenter)
        self.spinCenterY.setMaximum(9999)
        self.spinCenterY.setObjectName(_fromUtf8("spinCenterY"))
        self.horizontalLayout_3.addWidget(self.spinCenterY)
        self.verticalLayout_3.addWidget(self.groupCenter)
        self.groupCrop = QtGui.QGroupBox(self.EditingParamters)
        self.groupCrop.setToolTip(_fromUtf8("Crop image"))
        self.groupCrop.setCheckable(True)
        self.groupCrop.setChecked(False)
        self.groupCrop.setObjectName(_fromUtf8("groupCrop"))
        self.formLayout_4 = QtGui.QFormLayout(self.groupCrop)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_6 = QtGui.QLabel(self.groupCrop)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.spinRcrop = QtGui.QSpinBox(self.groupCrop)
        self.spinRcrop.setMaximum(9999)
        self.spinRcrop.setObjectName(_fromUtf8("spinRcrop"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinRcrop)
        self.verticalLayout_3.addWidget(self.groupCrop)
        self.groupRotate = QtGui.QGroupBox(self.EditingParamters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupRotate.sizePolicy().hasHeightForWidth())
        self.groupRotate.setSizePolicy(sizePolicy)
        self.groupRotate.setCheckable(True)
        self.groupRotate.setChecked(False)
        self.groupRotate.setObjectName(_fromUtf8("groupRotate"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupRotate)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.checkRot90 = QtGui.QCheckBox(self.groupRotate)
        self.checkRot90.setObjectName(_fromUtf8("checkRot90"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkRot90)
        self.label_3 = QtGui.QLabel(self.groupRotate)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.spinRotateDeg = QtGui.QDoubleSpinBox(self.groupRotate)
        self.spinRotateDeg.setDecimals(1)
        self.spinRotateDeg.setMinimum(-360.0)
        self.spinRotateDeg.setMaximum(360.0)
        self.spinRotateDeg.setObjectName(_fromUtf8("spinRotateDeg"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinRotateDeg)
        self.verticalLayout_3.addWidget(self.groupRotate)
        self.groupInvert = QtGui.QGroupBox(self.EditingParamters)
        self.groupInvert.setCheckable(True)
        self.groupInvert.setChecked(False)
        self.groupInvert.setObjectName(_fromUtf8("groupInvert"))
        self.verticalLayout_3.addWidget(self.groupInvert)
        self.verticalLayout.addWidget(self.EditingParamters)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.ViewingParameters = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ViewingParameters.sizePolicy().hasHeightForWidth())
        self.ViewingParameters.setSizePolicy(sizePolicy)
        self.ViewingParameters.setObjectName(_fromUtf8("ViewingParameters"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.ViewingParameters)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.checkAxisLim = QtGui.QCheckBox(self.ViewingParameters)
        self.checkAxisLim.setObjectName(_fromUtf8("checkAxisLim"))
        self.verticalLayout_2.addWidget(self.checkAxisLim)
        self.groupColormap = QtGui.QGroupBox(self.ViewingParameters)
        self.groupColormap.setObjectName(_fromUtf8("groupColormap"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupColormap)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.comboColormap = QtGui.QComboBox(self.groupColormap)
        self.comboColormap.setObjectName(_fromUtf8("comboColormap"))
        self.comboColormap.addItem(_fromUtf8(""))
        self.comboColormap.addItem(_fromUtf8(""))
        self.comboColormap.addItem(_fromUtf8(""))
        self.comboColormap.addItem(_fromUtf8(""))
        self.comboColormap.addItem(_fromUtf8(""))
        self.comboColormap.addItem(_fromUtf8(""))
        self.comboColormap.addItem(_fromUtf8(""))
        self.comboColormap.addItem(_fromUtf8(""))
        self.comboColormap.addItem(_fromUtf8(""))
        self.comboColormap.addItem(_fromUtf8(""))
        self.comboColormap.addItem(_fromUtf8(""))
        self.comboColormap.addItem(_fromUtf8(""))
        self.comboColormap.addItem(_fromUtf8(""))
        self.comboColormap.addItem(_fromUtf8(""))
        self.comboColormap.addItem(_fromUtf8(""))
        self.comboColormap.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboColormap)
        self.checkNormColormap = QtGui.QCheckBox(self.groupColormap)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkNormColormap.sizePolicy().hasHeightForWidth())
        self.checkNormColormap.setSizePolicy(sizePolicy)
        self.checkNormColormap.setObjectName(_fromUtf8("checkNormColormap"))
        self.horizontalLayout.addWidget(self.checkNormColormap)
        self.checkLogColormap = QtGui.QCheckBox(self.groupColormap)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkLogColormap.sizePolicy().hasHeightForWidth())
        self.checkLogColormap.setSizePolicy(sizePolicy)
        self.checkLogColormap.setObjectName(_fromUtf8("checkLogColormap"))
        self.horizontalLayout.addWidget(self.checkLogColormap)
        self.verticalLayout_2.addWidget(self.groupColormap)
        self.groupColorscale = QtGui.QGroupBox(self.ViewingParameters)
        self.groupColorscale.setCheckable(True)
        self.groupColorscale.setChecked(False)
        self.groupColorscale.setObjectName(_fromUtf8("groupColorscale"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupColorscale)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_7 = QtGui.QLabel(self.groupColorscale)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.spinCSmin = QtGui.QDoubleSpinBox(self.groupColorscale)
        self.spinCSmin.setDecimals(3)
        self.spinCSmin.setMinimum(-999999.0)
        self.spinCSmin.setMaximum(999999.0)
        self.spinCSmin.setObjectName(_fromUtf8("spinCSmin"))
        self.horizontalLayout_2.addWidget(self.spinCSmin)
        self.label_8 = QtGui.QLabel(self.groupColorscale)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_2.addWidget(self.label_8)
        self.spinCSmax = QtGui.QDoubleSpinBox(self.groupColorscale)
        self.spinCSmax.setDecimals(3)
        self.spinCSmax.setMinimum(-999999.0)
        self.spinCSmax.setMaximum(999999.0)
        self.spinCSmax.setObjectName(_fromUtf8("spinCSmax"))
        self.horizontalLayout_2.addWidget(self.spinCSmax)
        self.verticalLayout_2.addWidget(self.groupColorscale)
        self.groupGrids = QtGui.QGroupBox(self.ViewingParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupGrids.sizePolicy().hasHeightForWidth())
        self.groupGrids.setSizePolicy(sizePolicy)
        self.groupGrids.setCheckable(True)
        self.groupGrids.setChecked(False)
        self.groupGrids.setObjectName(_fromUtf8("groupGrids"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupGrids)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.checkCenterXYLines = QtGui.QCheckBox(self.groupGrids)
        self.checkCenterXYLines.setObjectName(_fromUtf8("checkCenterXYLines"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkCenterXYLines)
        self.label_4 = QtGui.QLabel(self.groupGrids)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.spinCalibConst = QtGui.QDoubleSpinBox(self.groupGrids)
        self.spinCalibConst.setMaximum(99999.0)
        self.spinCalibConst.setProperty("value", 1000.0)
        self.spinCalibConst.setObjectName(_fromUtf8("spinCalibConst"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.spinCalibConst)
        self.label_5 = QtGui.QLabel(self.groupGrids)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lineEGridVals = QtGui.QLineEdit(self.groupGrids)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEGridVals.sizePolicy().hasHeightForWidth())
        self.lineEGridVals.setSizePolicy(sizePolicy)
        self.lineEGridVals.setObjectName(_fromUtf8("lineEGridVals"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEGridVals)
        self.label_9 = QtGui.QLabel(self.groupGrids)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_9)
        self.linepTickVals = QtGui.QLineEdit(self.groupGrids)
        self.linepTickVals.setObjectName(_fromUtf8("linepTickVals"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.linepTickVals)
        self.checkXYgrid = QtGui.QCheckBox(self.groupGrids)
        self.checkXYgrid.setObjectName(_fromUtf8("checkXYgrid"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.checkXYgrid)
        self.verticalLayout_2.addWidget(self.groupGrids)
        self.verticalLayout.addWidget(self.ViewingParameters)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 386, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuF_ile = QtGui.QMenu(self.menubar)
        self.menuF_ile.setObjectName(_fromUtf8("menuF_ile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open = QtGui.QAction(MainWindow)
        self.action_Open.setText(_fromUtf8("&Open"))
        self.action_Open.setShortcut(_fromUtf8("Ctrl+O"))
        self.action_Open.setObjectName(_fromUtf8("action_Open"))
        self.action_Close = QtGui.QAction(MainWindow)
        self.action_Close.setObjectName(_fromUtf8("action_Close"))
        self.action_Center = QtGui.QAction(MainWindow)
        self.action_Center.setCheckable(True)
        self.action_Center.setObjectName(_fromUtf8("action_Center"))
        self.action_Rotate = QtGui.QAction(MainWindow)
        self.action_Rotate.setCheckable(True)
        self.action_Rotate.setObjectName(_fromUtf8("action_Rotate"))
        self.action_Save = QtGui.QAction(MainWindow)
        self.action_Save.setObjectName(_fromUtf8("action_Save"))
        self.action_Close_2 = QtGui.QAction(MainWindow)
        self.action_Close_2.setObjectName(_fromUtf8("action_Close_2"))
        self.action_Quit = QtGui.QAction(MainWindow)
        self.action_Quit.setObjectName(_fromUtf8("action_Quit"))
        self.action_Grid = QtGui.QAction(MainWindow)
        self.action_Grid.setObjectName(_fromUtf8("action_Grid"))
        self.actionOpen_Next = QtGui.QAction(MainWindow)
        self.actionOpen_Next.setText(_fromUtf8("Open &Next"))
        self.actionOpen_Next.setShortcut(_fromUtf8("Ctrl+N"))
        self.actionOpen_Next.setObjectName(_fromUtf8("actionOpen_Next"))
        self.actionOpen_Previous = QtGui.QAction(MainWindow)
        self.actionOpen_Previous.setText(_fromUtf8("Open &Previous"))
        self.actionOpen_Previous.setShortcut(_fromUtf8("Ctrl+P"))
        self.actionOpen_Previous.setObjectName(_fromUtf8("actionOpen_Previous"))
        self.actionCro_p = QtGui.QAction(MainWindow)
        self.actionCro_p.setObjectName(_fromUtf8("actionCro_p"))
        self.menuF_ile.addAction(self.action_Open)
        self.menuF_ile.addAction(self.actionOpen_Next)
        self.menuF_ile.addAction(self.actionOpen_Previous)
        self.menuF_ile.addAction(self.action_Save)
        self.menuF_ile.addSeparator()
        self.menuF_ile.addAction(self.action_Quit)
        self.menubar.addAction(self.menuF_ile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineFileName, self.pushNext)
        MainWindow.setTabOrder(self.pushNext, self.pushPrevious)
        MainWindow.setTabOrder(self.pushPrevious, self.groupCenter)
        MainWindow.setTabOrder(self.groupCenter, self.spinCenterX)
        MainWindow.setTabOrder(self.spinCenterX, self.spinCenterY)
        MainWindow.setTabOrder(self.spinCenterY, self.groupCrop)
        MainWindow.setTabOrder(self.groupCrop, self.spinRcrop)
        MainWindow.setTabOrder(self.spinRcrop, self.groupRotate)
        MainWindow.setTabOrder(self.groupRotate, self.checkRot90)
        MainWindow.setTabOrder(self.checkRot90, self.spinRotateDeg)
        MainWindow.setTabOrder(self.spinRotateDeg, self.checkAxisLim)
        MainWindow.setTabOrder(self.checkAxisLim, self.comboColormap)
        MainWindow.setTabOrder(self.comboColormap, self.checkNormColormap)
        MainWindow.setTabOrder(self.checkNormColormap, self.checkLogColormap)
        MainWindow.setTabOrder(self.checkLogColormap, self.groupColorscale)
        MainWindow.setTabOrder(self.groupColorscale, self.spinCSmin)
        MainWindow.setTabOrder(self.spinCSmin, self.spinCSmax)
        MainWindow.setTabOrder(self.spinCSmax, self.groupGrids)
        MainWindow.setTabOrder(self.groupGrids, self.checkCenterXYLines)
        MainWindow.setTabOrder(self.checkCenterXYLines, self.checkXYgrid)
        MainWindow.setTabOrder(self.checkXYgrid, self.spinCalibConst)
        MainWindow.setTabOrder(self.spinCalibConst, self.lineEGridVals)
        MainWindow.setTabOrder(self.lineEGridVals, self.linepTickVals)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "RawViewer", None, QtGui.QApplication.UnicodeUTF8))
        self.fileParameters.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.pushNext.setText(QtGui.QApplication.translate("MainWindow", "&Next", None, QtGui.QApplication.UnicodeUTF8))
        self.pushPrevious.setText(QtGui.QApplication.translate("MainWindow", "&Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.EditingParamters.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.groupCenter.setTitle(QtGui.QApplication.translate("MainWindow", "Center", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "X=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Y=", None, QtGui.QApplication.UnicodeUTF8))
        self.groupCrop.setTitle(QtGui.QApplication.translate("MainWindow", "Crop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "R=", None, QtGui.QApplication.UnicodeUTF8))
        self.groupRotate.setTitle(QtGui.QApplication.translate("MainWindow", "Rotate", None, QtGui.QApplication.UnicodeUTF8))
        self.checkRot90.setText(QtGui.QApplication.translate("MainWindow", "90 deg", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Degree", None, QtGui.QApplication.UnicodeUTF8))
        self.groupInvert.setTitle(QtGui.QApplication.translate("MainWindow", "Invert", None, QtGui.QApplication.UnicodeUTF8))
        self.ViewingParameters.setTitle(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.checkAxisLim.setText(QtGui.QApplication.translate("MainWindow", "Hold view", None, QtGui.QApplication.UnicodeUTF8))
        self.groupColormap.setTitle(QtGui.QApplication.translate("MainWindow", "Color map", None, QtGui.QApplication.UnicodeUTF8))
        self.comboColormap.setItemText(0, QtGui.QApplication.translate("MainWindow", "jet", None, QtGui.QApplication.UnicodeUTF8))
        self.comboColormap.setItemText(1, QtGui.QApplication.translate("MainWindow", "seismic", None, QtGui.QApplication.UnicodeUTF8))
        self.comboColormap.setItemText(2, QtGui.QApplication.translate("MainWindow", "coolwarm", None, QtGui.QApplication.UnicodeUTF8))
        self.comboColormap.setItemText(3, QtGui.QApplication.translate("MainWindow", "RdBu", None, QtGui.QApplication.UnicodeUTF8))
        self.comboColormap.setItemText(4, QtGui.QApplication.translate("MainWindow", "RdYlBu", None, QtGui.QApplication.UnicodeUTF8))
        self.comboColormap.setItemText(5, QtGui.QApplication.translate("MainWindow", "bone", None, QtGui.QApplication.UnicodeUTF8))
        self.comboColormap.setItemText(6, QtGui.QApplication.translate("MainWindow", "gray", None, QtGui.QApplication.UnicodeUTF8))
        self.comboColormap.setItemText(7, QtGui.QApplication.translate("MainWindow", "hot", None, QtGui.QApplication.UnicodeUTF8))
        self.comboColormap.setItemText(8, QtGui.QApplication.translate("MainWindow", "copper", None, QtGui.QApplication.UnicodeUTF8))
        self.comboColormap.setItemText(9, QtGui.QApplication.translate("MainWindow", "pink", None, QtGui.QApplication.UnicodeUTF8))
        self.comboColormap.setItemText(10, QtGui.QApplication.translate("MainWindow", "hsv", None, QtGui.QApplication.UnicodeUTF8))
        self.comboColormap.setItemText(11, QtGui.QApplication.translate("MainWindow", "cool", None, QtGui.QApplication.UnicodeUTF8))
        self.comboColormap.setItemText(12, QtGui.QApplication.translate("MainWindow", "spring", None, QtGui.QApplication.UnicodeUTF8))
        self.comboColormap.setItemText(13, QtGui.QApplication.translate("MainWindow", "summer", None, QtGui.QApplication.UnicodeUTF8))
        self.comboColormap.setItemText(14, QtGui.QApplication.translate("MainWindow", "autumn", None, QtGui.QApplication.UnicodeUTF8))
        self.comboColormap.setItemText(15, QtGui.QApplication.translate("MainWindow", "winter", None, QtGui.QApplication.UnicodeUTF8))
        self.checkNormColormap.setText(QtGui.QApplication.translate("MainWindow", "Norm", None, QtGui.QApplication.UnicodeUTF8))
        self.checkLogColormap.setText(QtGui.QApplication.translate("MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.groupColorscale.setTitle(QtGui.QApplication.translate("MainWindow", "Color scale", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "min=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "max=", None, QtGui.QApplication.UnicodeUTF8))
        self.groupGrids.setTitle(QtGui.QApplication.translate("MainWindow", "Grids", None, QtGui.QApplication.UnicodeUTF8))
        self.checkCenterXYLines.setText(QtGui.QApplication.translate("MainWindow", "Center lines", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Calib. const.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Egrid=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "pticks=", None, QtGui.QApplication.UnicodeUTF8))
        self.checkXYgrid.setText(QtGui.QApplication.translate("MainWindow", "X/Y grid", None, QtGui.QApplication.UnicodeUTF8))
        self.menuF_ile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Close.setText(QtGui.QApplication.translate("MainWindow", "&Close", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Center.setText(QtGui.QApplication.translate("MainWindow", "&Center", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Rotate.setText(QtGui.QApplication.translate("MainWindow", "&Rotate", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Close_2.setText(QtGui.QApplication.translate("MainWindow", "&Close", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Grid.setText(QtGui.QApplication.translate("MainWindow", "&Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCro_p.setText(QtGui.QApplication.translate("MainWindow", "Cro&p", None, QtGui.QApplication.UnicodeUTF8))

